### ISSUE TITLE
Question: Is there a destructor?

### ISSUE THREAD

**Issue by MikaelElkiaer** [michaelbromley/angular-es6#9]
I was wondering if there was a simple construct for defining a destructor, similar and opposite to the `constructor()`.

Or, do we still need `$scope.$on('$destroy', ...)`?

**Comment by michaelbromley** [comment]
Hi,

ES6 does not define any kind of class destructor (see http://stackoverflow.com/a/29335934/772859).

`$scope.$on('$destroy')` would make sense for directives, and you could effectively simulate a destructor by just invoking a given class method when the `$destroy` event is fired.

For other types of injectable (service, factory, provider) the concept of a destructor is probably not useful, since they are singletons which last for the duration of the app's life.
